# the name of the target operating system
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR  Arm)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

# search for program/library/include in the build host directories
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(TOOLCHAIN_PREFIX arm-none-eabi)

get_filename_component(CMAKE_TOOLCHAIN_BIN_PATH "${CMAKE_C_COMPILER}" DIRECTORY)
get_filename_component(CMAKE_TOOLCHAIN_EXT "${CMAKE_C_COMPILER}" EXT)

SET(CMAKE_LINKER        "${CMAKE_TOOLCHAIN_BIN_PATH}/${TOOLCHAIN_PREFIX}-ld${CMAKE_TOOLCHAIN_EXT}" CACHE INTERNAL "" )
SET(CMAKE_OBJCOPY       "${CMAKE_TOOLCHAIN_BIN_PATH}/${TOOLCHAIN_PREFIX}-objcopy${CMAKE_TOOLCHAIN_EXT}")
SET(CMAKE_SIZE          "${CMAKE_TOOLCHAIN_BIN_PATH}/${TOOLCHAIN_PREFIX}-size${CMAKE_TOOLCHAIN_EXT}")
SET(CMAKE_NM          "${CMAKE_TOOLCHAIN_BIN_PATH}/${TOOLCHAIN_PREFIX}-nm${CMAKE_TOOLCHAIN_EXT}")
